### ISSUE TITLE
Does it work with Audio Hijack Pro 3 or not at all?

### ISSUE THREAD

**Issue by hanoii** [alexjohnj/spotijack#4]
The README implies it doesn't, but the also mentions it.

**Comment by alexjohnj** [comment]
Spotijack doesn't work with Audio Hijack 3 because Audio Hijack 3 does not support AppleScript. However, you need to use Audio Hijack 3 to install the _Instant On_ recording plugin (called _ACE_ now I believe) because the version that comes with Audio Hijack Pro 2 is too old for today's versions of macOS.
